services:
  - type: web
    name: ia-sinais-ob
    env: python
    runtime: python
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements-render.txt && python startup_check.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ia-sinais-db
          property: connectionString
      - key: IQ_EMAIL
        sync: false
      - key: IQ_PASSWORD
        sync: false
      - key: PYTHONPATH
        value: .

databases:
  - name: ia-sinais-db
    plan: free